apiVersion: v1
data:
  policy.csv: |
    g, khanhcmlab:devops, role:admin
    g, khanhcmlab, role:readonly
  policy.default: ""
  policy.matchMode: glob
  scopes: '[groups]'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: argocd
    meta.helm.sh/release-namespace: argocd
  creationTimestamp: "2026-05-16T13:00:42Z"
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/version: v3.4.2
    helm.sh/chart: argo-cd-9.5.14
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "262307"
  uid: 9b177b02-1491-4d93-9775-cb6e871b0feb
